service: serverless

app: my-first-app
org: willtorres10

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: somar
          method: get
